name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Please provide a clear and concise description of the bug.
      placeholder: "Describe the bug here..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: "Expected behavior..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Add screenshots here..."
