name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: Provide a detailed description of the feature you are requesting.
      placeholder: "Describe the feature..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: Explain the use case or problem this feature would address.
      placeholder: "Explain the use case..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Additional context..."
